#config.yml
spool_dir: /usr/amoeba/spool/workspace/LAND_SRF_RD_2020/
msm_spool_dir: /usr/amoeba/spool/workspace/RD_SRFC_10V_MSM/
cl_data_spool_dir: /usr/amoeba/spool/workspace/LAND_SRF_RD_SOILPREC/cl_data/
rd_table_winter: RD_TABLE_10V_WINTER.xml
rd_table_summer: RD_TABLE_10V_SUMMER.xml
rd_table_winter_spool: RD_TABLE_10V_WINTER.pst
rd_table_summer_spool: RD_TABLE_10V_SUMMER.pst
rd_obs_point_list_spool: /usr/amoeba/spool/workspace/OBSERVATION_PREC_INTEG/OBS_POINT_LIST.pst
rd_analysis_point_list_spool: /usr/amoeba/spool/workspace/OBSERVATION_PREC_INTEG/ANALYSIS_POINT_LIST.pst
c3op_change_spool: /usr/amoeba/spool/workspace/RD_SRFC_10V_C3OP/c3op_change_data.pst
msm_change_spool: msm_change_data.pst
rd_mk2_point_list_spool: /usr/amoeba/spool/workspace/OBSERVATION_PREC_INTEG/MK2_POINT_LIST.pst
#rd_level3_time_list_spool: /usr/amoeba/spool/workspace/OBSERVATION_PREC_INTEG/level3_time_list.pst
rd_level3_time_list_spool: /usr/amoeba/spool/workspace/OBSERVATION_PREC_INTEG/road_close_2.pst
rd_latest_time_list: /usr/amoeba/spool/workspace/OBSERVATION_PREC_INTEG/latest_time_list.pst
szid_asmid_rain_pid_spool: /usr/amoeba/spool/workspace/LAND_SRF_RD_SOILPREC/szid_asmid_rain_pid.pst
CL_version: /usr/amoeba/spool/workspace/LAND_SRF_RD_SOILPREC/cl_version.pst
jbhonsi_manualentered_spool: jbhonsi_manualentered.pst
honsi_winter_obsid_spool: winter_obsid_honsi.pst
mk2_prec_table: observation_prec_integ
mk2_scale_table: observation_prec_scale
mk2_soilp_table: obs_soilp_scale_index
mk2_winter_table: observation_winter
"411024529":
  winter_dataid16: "0200600011024609"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_percentile_30_raw
  summer_dataid16: "0200600011024616"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_percentile_30_raw
  c3op_dataid16: "0200600011024936"
  c3op_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_30_PRANK_filter
"411024528":
  winter_dataid16: "0200600011024610"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_percentile_40_raw
  summer_dataid16: "0200600011024617"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_percentile_40_raw
  c3op_dataid16: "0200600011024942"
  c3op_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_40_PRANK_filter
"411024527":
  winter_dataid16: "0200600011024611"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_percentile_50_raw
  summer_dataid16: "0200600011024618"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_percentile_50_raw
  c3op_dataid16: "0200600011024943"
  c3op_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_50_PRANK_filter
"411024588":
  winter_dataid16: "0200600011024627"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_percentile_20_raw
  summer_dataid16: "0200600011024628"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_percentile_20_raw
"411024679":
  winter_dataid16: "0200600011024681"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_SCNRO_heavysnow_raw
"411024713":
  winter_dataid16: "0200600011024699"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_percentile_10
  summer_dataid16: "0200600011024700"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_percentile_10
"412010210":
  summer_dataid16: "0200600011024701"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak1_main20
"412010211":
  summer_dataid16: "0200600011024702"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak5_main20
"412010212":
  summer_dataid16: "0200600011024703"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak1_main30
"412010213":
  summer_dataid16: "0200600011024704"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak5_main30
"412010216":
  summer_dataid16: "0200600011024730"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak1_main40
"412010217":
  summer_dataid16: "0200600011024731"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak1_main50
"412010218":
  summer_dataid16: "0200600011024732"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak5_main40
"412010219":
  summer_dataid16: "0200600011024733"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_peak5_main50
"411024753":
  winter_dataid16: "0200600011024755"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_analogos_JP
"411024754":
  winter_dataid16: "0200600011024756"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_analogos_HOK
"411024758":
  winter_dataid16: "0200600011024761"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_pressure_pattern
"411024831":
  summer_dataid16: "0200600011024835"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_pressure_pattern
"411024882":
  winter_dataid16: "0200600011024905"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_sharp_main20
"411024883":
  winter_dataid16: "0200600011024906"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_sharp_main40
"411024884":
  winter_dataid16: "0200600011024907"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_sharp_main50
"411024885":
  winter_dataid16: "0200600011024908"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_sharp_main60
"411024900":
  winter_dataid16: "0200600011024909"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_60
"411024901":
  winter_dataid16: "0200600011024910"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_80
#
"411026101":
  winter_dataid16: "0200600011026126"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_heavysnow_pressure_pattern_raw
"411026102":
  winter_dataid16: "0200600011026127"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_snowpeak_zerosnow_40
"411026103":
  winter_dataid16: "0200600011026128"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_snowpeak_zerosnow_30
"411026104":
  winter_dataid16: "0200600011026129"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_snowpeak_zerosnow_pressure_pattern
"411026105":
  winter_dataid16: "0200600011026130"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_snowpeak_msmphase_40
"411026106":
  winter_dataid16: "0200600011026131"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_snowpeak_msmphase_30
"411026107":
  winter_dataid16: "0200600011026132"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_snowpeak_zerosnow_msmphase_40
"411026108":
  winter_dataid16: "0200600011026133"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_snowpeak_zerosnow_msmphase_30
"411026109":
  winter_dataid16: "0200600011026134"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_40
"411026110":
  winter_dataid16: "0200600011026135"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_30
"411026111":
  winter_dataid16: "0200600011026136"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_20
"411026112":
  winter_dataid16: "0200600011026137"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_pressure_pattern
"411026113":
  winter_dataid16: "0200600011026138"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_msmphase_50
"411026114":
  winter_dataid16: "0200600011026139"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_msmphase_40
"411026115":
  winter_dataid16: "0200600011026140"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_msmphase_30
"411026116":
  winter_dataid16: "0200600011026141"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_msmphase_20
"411026117":
  winter_dataid16: "0200600011026142"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_msmphase_50
"411026118":
  winter_dataid16: "0200600011026143"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_msmphase_40
"411026119":
  winter_dataid16: "0200600011026144"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_msmphase_30
"411026120":
  winter_dataid16: "0200600011026145"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_msmphase_20
"411026121":
  winter_dataid16: "0200600011026146"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_ownphase_40
"411026122":
  winter_dataid16: "0200600011026147"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_zerosnow_ownphase_30
# 2025
"411026171":
  winter_dataid16: "0200600011026232"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_80_v2
"411026172":
  winter_dataid16: "0200600011026233"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_60_v2
"411026173":
  winter_dataid16: "0200600011026234"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_50_v2
"411026174":
  winter_dataid16: "0200600011026235"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_40_v2
"411026175":
  winter_dataid16: "0200600011026236"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_30_v2
"411026176":
  winter_dataid16: "0200600011026237"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_20_v2
"411026177":
  winter_dataid16: "0200600011026238"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_15_v2
"411026178":
  winter_dataid16: "0200600011026239"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_10_v2
"411026179":
  winter_dataid16: "0200600011026240"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_05_v2
#
"412010280":
  summer_dataid16: "0200600011026319"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_HVRNP_main10
"412010281":
  summer_dataid16: "0200600011026320"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_HVRNP_main20
"412010282":
  summer_dataid16: "0200600011026321"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_HVRNP_main30
#
"411026377":
  winter_dataid16: "0200600011026383"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_01
"411026097":
  winter_dataid16: "0200600011026384"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_05
"411026098":
  winter_dataid16: "0200600011026385"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_15
"411026378":
  winter_dataid16: "0200600011026386"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_70
"411026379":
  winter_dataid16: "0200600011026387"
  winter_data_name: WNI_SRF_VSCAL_RD_snowremoval_PRCNTL_90
#
"411026332":
  summer_dataid16: "0200600011026358"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_HVRNP_peak_multimodel_main10
"411026333":
  summer_dataid16: "0200600011026359"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_HVRNP_peak_multimodel_main20
"411026334":
  summer_dataid16: "0200600011026360"
  summer_data_name: WNI_SRF_VSCAL_RD_routepatrol_HVRNP_peak_multimodel_main30
#
edit_output:
  winter_tagid: 411024614
  winter_dataid16: "0200600011024614"
  winter_data_name: "WNI_SRF_VSCAL_RD_snowremoval_preview"
  winter_deliver: 1
  summer_dataid16: "0200600011024620"
  summer_data_name: "WNI_SRF_VSCAL_RD_routepatrol_preview"
  rdfreeze_tagid: 411024615
  rdfreeze_dataid16: "0200600011024615"
  rdfreeze_dataname: WNI_SRF_VSCAL_RD_snowremoval_NOPRFZ
  rdfreeze_deliver: 1
wx_conv:
  110: 100
  150: 100
  250: 200
  310: 300
  350: 300
  360: 300
  460: 400
  500: 430
disthost: localhost
distport: 32000
road_closed_level:
  - 40
  - 50
  - 60
  - 70
# dewtmp
dewtmp_spool_avg: /usr/amoeba/spool/workspace/SPOOL_DEW_POINT/avg_dew_zone.dmp
dewtmp_zone_path: /usr/amoeba/spool/workspace/SPOOL_DEW_POINT/RD_ZONE.pst
# mail
email_send: 1
email_addrs:
  - naga-a@wni.com
  - yamayo@wni.com
  - koshiy@wni.com
  - yama-t@wni.com
# road close
second_thd: 2.5
# lock file make raw data winter
lock_file_raw_winter:
  "411024529": make_raw_winter_lock_1
  "411024528": make_raw_winter_lock_1
  "411024527": make_raw_winter_lock_1
  "411024588": make_raw_winter_lock_1
  "411024679": make_raw_winter_lock_1
  "411024713": make_raw_winter_lock_1
#  "411024753": make_raw_winter_lock_1
#  "411024754": make_raw_winter_lock_1
  "411024758": make_raw_winter_lock_1
  "411024882": make_raw_winter_lock_1
  "411024883": make_raw_winter_lock_1
  "411024884": make_raw_winter_lock_1
#  "411024885": make_raw_winter_lock_1
  "411024900": make_raw_winter_lock_1
  "411024901": make_raw_winter_lock_1
  "411026177": make_raw_winter_lock_1
  "411026178": make_raw_winter_lock_1
  "411026179": make_raw_winter_lock_1
  "411026377": make_raw_winter_lock_1
# 16
  "411026101": make_raw_winter_lock_2
  "411026102": make_raw_winter_lock_2
  "411026103": make_raw_winter_lock_2
  "411026104": make_raw_winter_lock_2
  "411026105": make_raw_winter_lock_2
  "411026106": make_raw_winter_lock_2
  "411026107": make_raw_winter_lock_2
  "411026108": make_raw_winter_lock_2
  "411026109": make_raw_winter_lock_2
  "411026110": make_raw_winter_lock_2
  "411026111": make_raw_winter_lock_2
  "411026171": make_raw_winter_lock_2
  "411026172": make_raw_winter_lock_2
  "411026173": make_raw_winter_lock_2
  "411026097": make_raw_winter_lock_2
  "411026378": make_raw_winter_lock_2
# 16
  "411026112": make_raw_winter_lock_3
  "411026113": make_raw_winter_lock_3
  "411026114": make_raw_winter_lock_3
  "411026115": make_raw_winter_lock_3
  "411026116": make_raw_winter_lock_3
  "411026117": make_raw_winter_lock_3
  "411026118": make_raw_winter_lock_3
  "411026119": make_raw_winter_lock_3
  "411026120": make_raw_winter_lock_3
  "411026121": make_raw_winter_lock_3
  "411026122": make_raw_winter_lock_3
  "411026174": make_raw_winter_lock_3
  "411026175": make_raw_winter_lock_3
  "411026176": make_raw_winter_lock_3
  "411026098": make_raw_winter_lock_3
  "411026379": make_raw_winter_lock_3
# 16
# lock file make raw data summer
lock_file_raw_summer: make_raw_summer_lock
# raw
raw_host: gpec-zf7-vmg
