[env]
TIME_INTERVAL=24
TITLE=PREC SCALE ARRANGE FCST MIP
TABLE_NAME=prec_scale_arrange_fcst_mip
element_list=INDEX_rain,keep_count
EXPIRE=1 day

[projection]
grid_type=POINT2

[INDEX_rain]
#データ型
data_type=char
#単位
units=char
#データ名称
long_name=index_rain
#最小値
valid_min=0
#最大値
valid_max=99
#フィル値
fill_value=-99
#欠測値
missing_value=-99
#printfフォーマット
C_format=%d

[keep_count]
#データ型
data_type=long
#単位
units=mm-1
#データ名称
long_name=keep_count
#最小値
valid_min=0
#最大値
valid_max=999999
#フィル値
fill_value=-1
#欠測値
missing_value=-1
#printfフォーマット
C_format=%d
