[env]
TIME_INTERVAL=24
TITLE=PREC SCALE ARRANGE MIP
TABLE_NAME=prec_scale_arrange_mip
element_list=INDEX_rain_raw,INDEX_rain
EXPIRE=1 day

[projection]
grid_type=POINT2

[INDEX_rain_raw]
#データ型
data_type=char
#単位
units=char
#データ名称
long_name=index_rain_raw
#最小値
valid_min=0
#最大値
valid_max=99
#フィル値
fill_value=-99
#欠測値
missing_value=-99
#printfフォーマット
C_format=%d

[INDEX_rain]
#データ型
data_type=char
#単位
units=char
#データ名称
long_name=index_rain
#最小値
valid_min=0
#最大値
valid_max=99
#フィル値
fill_value=-99
#欠測値
missing_value=-99
#printfフォーマット
C_format=%d
