[env]
TIME_INTERVAL=24
TITLE=RAIN_DIM_GROUP
TABLE_NAME=rain_dim_group
element_list=GROUP_ID
EXPIRE=30 day

[projection]
#座標系
grid_type=POINT2

[GROUP_ID]
#データ型
data_type=short
#単位
units=bit
#データ名称
long_name=RAIN DIM GROUP ID
#最小値
valid_min=1
#最大値
valid_max=99
#フィル値
fill_value=0
#欠測値
missing_value=-1
#printfフォーマット
C_format=%d
