#config.yml
# 出力スプールファイル
output_spool_file: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/risk_scale_rain_output.pst
# マイクロネット前処理出力mk2テーブル
mk2_prec_table: rain_scale_mnet_prec
# マイクロネット前処理排他用ファイル
spool_prec_path: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/micronet_precipitation.pst
# 1kmのメッシュ情報
area_mesh_kakuho_dir: /usr/amoeba/spool/workspace/RISK_SCALE_COMMON/
area_mesh_kakuho_name: area_mesh_kakuho_map
# 5kmのメッシュ情報
area_mesh_compas_path: /usr/amoeba/spool/workspace/RISK_SCALE_COMMON/area_mesh_compas_map.pst
# 確報のスプールディレクトリ
spool_kakuho_dir: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/kakuho/
# 確報のスプール保存期限
spool_kakuho_expire: 60
# COMPASS雨量前処理出力mk2テーブル
mk2_compass_prec_table: compass_prec_counter
mk2_compass_prec_int_table: compass_prec_accum
mk2_compass_prec_mesh_counter: compass_prec_mesh_counter
mk2_compass_prec_mesh_prst_max: compass_prec_mesh_prst_max
# COMPASSのスプールファイル
spool_compas_path: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/rain_scale_compass.pst
#created_compas_path: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/created_compass.pst
# COMPASS前処理排他用ファイル
spool_compass_prec_path: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/compass_precipitation.pst
# 編集されたスケール値のスプールファイル
spool_edit_scale_path: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/edit_risk_scale.pst
# 編集されたスケール値のスプール保存期限
spool_edit_expire: 5
# ビジネスデータのスプールファイル
table_basic_rain_dump_dir: /usr/amoeba/spool/workspace/RISK_SCALE_COMMON/
table_basic_rain_dump_name: table_dim_basic_rain_info
table_10vscal_dump_path: /usr/amoeba/spool/workspace/RISK_SCALE_COMMON/table_srf_10vscal_rain_dim.pst
# 乱高下防止処理用スケールの過去値のスプールファイル
spool_ft12_scale_path: /usr/amoeba/spool/workspace/PRCRIN_RISK_SCALE/ft12_risk_scale.pst
# 乱高下防止処理設定
ft12_keep_time_1: 90
ft12_keep_time_2: 60
ft12_keep_level_1: 1
keep_level_60: 0.5
keep_level_combine_60: 0.5
# deliver to amdistserv
deliver_host: localhost
deliver_port: 32000
# 降水確報フィルター
kakuho_filter: 0.5
# 編集機能
edit_data: 1
# 大雨に関するリスクスケール分割数
rain_group_count: /usr/amoeba/spool/workspace/RISK_SCALE_COMMON/rain_group_count.pst
# 大雨に関するリスクスケールグループmk2テーブル
mk2_prec_group_table: rain_dim_group
# 乱高下防止処理用スケールの過去値のmk2テーブル
mk2_scale_table: prec_scale_arrange_dim
mk2_scale_near_table: prec_scale_arrange_near_dim
mk2_scale_fcst_table: prec_scale_arrange_fcst_dim
# 解析雨量10分60分雨量第3便mk2テーブル
mk2_analysis_prec_03_table: analysis_prec_03
# 解析雨量一雨積算雨量mk2テーブル
mk2_analysis_prec_integ_table: analysis_prec_integ
# 解析雨量3h24h積算雨量mk2テーブル
mk2_analysis_prec_accum_table: analysis_prec_accum
mk2_analysis_prec_counter_table: analysis_prec_counter
# 解析雨量前処理出力mk2テーブル
mk2_analysis_prec_table: rain_scale_analisys_prec
mk2_analysis_prec_mesh_counter: analisys_prec_mesh_counter
mk2_analysis_prec_mesh_counter_10min: analisys_prec_mesh_counter_10min
mk2_analysis_prec_mesh_accum: analisys_prec_mesh_accum
mk2_analysis_prec_mesh_accum_max: analisys_prec_mesh_accum_max
# 1kmのメッシュ情報
area_mesh_kakuho_path: /usr/amoeba/spool/workspace/RISK_SCALE_COMMON/area_mesh_kakuho_map.pst
# 乱高下防止処理の確報ロジック適用最終FT
scale_arrange_nowcast: 2
