[ELEMENT_NAME]
grib_edition	= 2
0,0,0	= Temperature
1,1	= RelativeHumidity
2,2	= U_componentOfWind
2,3	= V_componentOfWind
2,8	= Omega
3,5	= GeopotentialHeight

#==========================================================================
# テーブル名と座標ごとのパラメータからエリア名を取得するための設定
# 座標ごとのパラメータは下記の [GRID_KEY] で定義される。
#
# テーブル名: msm_upper_rd_adjust
# エリア名: MSM_UPPER
[AREA]
msm_upper_rd_adjust,47600000,120000000,22400000,150000000	= MSM_UPPER

[GRID_KEY]
0	= La1,Lo1,La2,Lo2

[XY_POINTNUM_KEY]
0	= Ni,Nj

# ==============================================================================
# 処理対象とする値
# セクション名は "テーブル名" + "_ALLOW_VALUE" で付与する。
# 右辺値群の頭に except を付けると、以降に列挙されたもの以外の値を
# 処理対象とする。
#
#[msm_upper_rd_adjust_ALLOW_VALUE]
#level   = 100000-ISBL,97500-ISBL,95000-ISBL,92500-ISBL,90000-ISBL,85000-ISBL,80000-ISBL,70000-ISBL,60000-ISBL,50000-ISBL
